### ISSUE TITLE
مشکل

### ISSUE THREAD

**Issue by mhpourtaghi** [azavaxhuman/IPTABLE-Tunnel-multi-port#1]
سلام وقتتون بخیر 
 اسکریپت مشکل داره چون چندین بار اجرا کردم تانل نشد سرور اولیمون رو تانل کردیم ولی  سرور دوممون تانل نمیشه چندین بار اسکریپت رو حدف و دوباره نصب کردیم 
 ipv6 تانل 
و این پینگ بلاکر چیه ؟
آیپی v4 تانل میشه اما 
تانل v6 نه

**Comment by azavaxhuman** [comment]
خب این اسکریپت فقط برای ipv4 ساختهشده
