### ISSUE TITLE
dds-tunnel: command not found

### ISSUE THREAD

**Issue by SaeedZareen** [azavaxhuman/IPTABLE-Tunnel-multi-port#2]
درود
برای اجرا این اسکریپت بعد از چند روز که از نصب گذشته دستور dds-tunnel رو میزنم که خروجی میگه همچین کامندی وجود نداره///

**Comment by azavaxhuman** [comment]
در حالت عادی که چنین چیزی ممکن نیست ، کار خاصی روی سرورتون انجام ندادین؟

**Comment by SaeedZareen** [comment]
Na

**Comment by azavaxhuman** [comment]
اسکریپت رو مجددا نصب کنین نباید مشکلی باشه ، اگر بود میتونین هربار فایل tunnel.sh رو با این دستور اجرا کنین تا منو باز بشه
bash /root/dds-tunnel/tunnel.sh
