### ISSUE TITLE
امکان استفاده از ipv6

### ISSUE THREAD

**Issue by webadminlist** [azavaxhuman/IPTABLE-Tunnel-multi-port#3]
درود بر شما
ممنونم بابت زحماتتون
امکانش هست ipv6 هم اضافه کنید؟

**Comment by webadminlist** [comment]
برای ipv6 حالت لود بالانسر داشته باشه
مثلا 5 تا ipv6 بدیم که خودش لود بالانس کنه

**Comment by azavaxhuman** [comment]
بهتره از نرم افزار های دیگه ای استفاده کنید برای اینکار مثل haproxy
